version: '3'
services:
  db:
    image: mysql:latest
    container_name: django_db
    environment:
      DB_HOST: db
      DB_NAME: django_db
      DB_USER: root
      DB_PASS: root
      DB_ROOT_PASS: root
    restart: always
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros_django
    image: ros_django
    environment:
      DB_HOST: db
      DB_NAME: django_db
      DB_USER: root
      DB_PASS: root
      DB_ROOT_PASS: root
    ports:
      - "8001:8000"
    depends_on:
      - db
    links:
      - db
