version: '3'

services:
  db:
    image: mysql:latest
    container_name: pure_db
    environment:
      DB_HOST: db
      MYSQL_DATABASE: ros_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root   
    restart: always 
    ports:
      - 3306:3306
    

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pure_app
    environment:
      DB_HOST: db
      DB_NAME: ros_db
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - 8001:8000
    depends_on:
      - db
    links:
      - db