# Generated by Django 4.2.6 on 2023-10-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='approval_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='bling_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='client_trasmittal_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='doc_return_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='doc_revision_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='document_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='ros_transmittal_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
