# Generated by Django 4.2.6 on 2023-10-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdmldocumentdetail',
            name='doc_revision_no',
            field=models.CharField(default=52, max_length=100),
            preserve_default=False,
        ),
    ]
