# Generated by Django 4.1.11 on 2023-10-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ros_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUserPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission_name", models.CharField(max_length=100)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ros_app.customuserroles",
                    ),
                ),
            ],
        ),
    ]
