# Generated by Django 4.1.11 on 2023-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ros_app", "0002_customuserpermissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuserroles",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="auth.permission"),
        ),
    ]
