# Generated by Django 4.2.6 on 2023-10-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0002_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customroles',
            old_name='username',
            new_name='name',
        ),
    ]
