# Generated by Django 4.2.6 on 2023-10-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0002_alter_vdmldocumentdetail_approval_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customroles',
            old_name='name',
            new_name='modalRoleName',
        ),
    ]
