# Generated by Django 4.2.6 on 2023-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0002_vdmldocumentdetail_doc_revision_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdml_document',
            name='ses_doc_no',
            field=models.CharField(default=54, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vdml_document',
            name='document_size',
            field=models.CharField(blank=True, choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('LEGAL', 'LEGAL'), ('LETTER', 'LETTER')], default='A4', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdml_document',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
