# Generated by Django 4.2.6 on 2023-10-05 11:18

from django.db import migrations, models
import django.db.models.deletion
import ros_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0003_remove_customuser_picture_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture for the user.', null=True, upload_to=ros_app.models.user_directory_path, verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Assign a role to the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ros_app.customroles', verbose_name='Role'),
        ),
    ]
