# Generated by Django 4.2.6 on 2023-10-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0003_rename_name_customroles_modalrolename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customroles',
            old_name='modalRoleName',
            new_name='name',
        ),
    ]
