# Generated by Django 4.1.11 on 2023-10-03 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ros_app", "0003_customuserroles_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuserpermissions",
            name="assigned_to",
        ),
    ]
