# Generated by Django 4.2.6 on 2023-10-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0003_vdml_document_ses_doc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='actual_returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='approval_rev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='blng_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='client_transmittal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='doc_revision_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='forecast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='issue_of_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='planned_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='ros_transmittal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdmldocumentdetail',
            name='se_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
