# Generated by Django 4.2.6 on 2023-10-05 09:41

from django.db import migrations, models
import ros_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0004_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture for the user.', null=True, upload_to=ros_app.models.user_directory_path, verbose_name='Profile Picture'),
        ),
    ]
