# Generated by Django 4.2.6 on 2023-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0005_alter_customroles_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customroles',
            name='permission',
            field=models.ManyToManyField(related_name='roles', to='ros_app.custompermissions'),
        ),
    ]
