# Generated by Django 4.2.6 on 2023-10-06 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0006_alter_customroles_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('client_name', models.CharField(max_length=100, unique=True)),
                ('cpm_name', models.TextField()),
                ('cpm_email', models.EmailField(max_length=254)),
                ('cpm_phone', models.CharField(max_length=20)),
                ('cdm_name', models.CharField(max_length=255)),
                ('cdm_email', models.EmailField(max_length=254)),
                ('cdm_phone', models.CharField(max_length=20)),
                ('document_manager', models.ForeignKey(blank=True, help_text='Assign a document manager to the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Document Manager')),
                ('project_manager', models.ForeignKey(blank=True, help_text='Assign a project manager to the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
        ),
    ]
