# Generated by Django 4.2.6 on 2023-10-07 05:07

from django.db import migrations
import ros_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ros_app', '0007_projects'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', ros_app.models.CustomUserManager()),
            ],
        ),
    ]
